### ISSUE TITLE
Backend Change to Jekyll and Ruby

### ISSUE THREAD

**Issue by Anindyadeep** [CORD-ai/cord-website#12]
Here several items additions are actually hard coded. But several of the things like:
- addition of new members
- addition of new projects / blogs / sessions 
etc 
must be automated. One way is to use Jekyll. We can use `yaml` files to update new items. 

So this is how it should work. Suppose we have this file called `members.yaml`. Here we add these items:

```yml
- name: Will
  img: logo.jpg
  location: London, UK
  linkedIn : ---
  GitHub : ---
  Website : ---
  Team : --- (like core / community manager / contributor)
  

- name: Amanda
  img: amanda.jpg
  location: New York City, USA
  page-name: amanda.html
  GitHub : ---
  Website : ---
  Team : --- (like core / community manager / contributor)

- name: Aaron
  img: aaron.jpg
  location: London, UK
  page-name: aaron.html
  GitHub : ---
  Website : ---
  Team : --- (like core / community manager / contributor)

- name: Swift
  img: swift.jpg
  location: New York City, USA
  page-name: swift.html
  GitHub : ---
  Website : ---
  Team : --- (like core / community manager / contributor)

```

This will automatically create the cards on the teams website and group them as well w.r.t. the team they belong to. This same thing should be done to `Our Work` section. 

Also, we can use `React` if the contributors feel this same thing could be done using that in faster and easily.
